version: "3.8"

services:
  backend:
    build:
      context: .  # Usa a raiz como diret칩rio de build do backend
      dockerfile: Dockerfile  # O Dockerfile das APIs est치 na raiz
    image: rodolfogaspar86/fiap_95aoj_smart_park-backend:latest  # Imagem do backend no reposit칩rio
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./BackOffice-SmartPark/backoffice-smartpark  # Caminho correto do frontend
      dockerfile: Dockerfile  # Dockerfile dentro dessa pasta
      args:
        - --no-cache
    image: rodolfogaspar86/fiap_95aoj_smart_park-frontend:latest  # Imagem do frontend no reposit칩rio
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
